export enum Instrument {
    PIANO, // 0 = Piano (air)
    DOUBLE_BASS, // 1 = Double Bass (wood)
    BASS_DRUM, // 2 = Bass Drum (stone)
    SNARE, // 3 = Snare Drum (sand)
    CLICK, // 4 = Click (glass)
    GUITAR, // 5 = Guitar (wool)
    FLUTE, // 6 = Flute (Clay)
    BELL, // 7 = Bell (Block of Gold)
    CHIME, // 8 = Chime (Packed Ice)
    XYLOPHONE, // 9 = Xylophone (Bone Block)
    IRONXYLOPHONE, // 10 = Iron Xylophone (Iron Block)
    COWBELL, // 11 = Cow Bell (Soul Sand)
    DIDGERIDOO, // 12 = Didgeridoo (Pumpkin)
    BIT, // 13 = Bit (Block of Emerald)
    BANJO, // 14 = Banjo (Hay)
    PLING //15 = Pling (Glowstone)
}